# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_dlg(object):
    def setupUi(self, search_dlg):
        search_dlg.setObjectName("search_dlg")
        search_dlg.resize(325, 460)
        self.verticalLayout = QtWidgets.QVBoxLayout(search_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(search_dlg)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(search_dlg)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(search_dlg)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(search_dlg)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(search_dlg)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(search_dlg)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(search_dlg)
        QtCore.QMetaObject.connectSlotsByName(search_dlg)

    def retranslateUi(self, search_dlg):
        _translate = QtCore.QCoreApplication.translate
        search_dlg.setWindowTitle(_translate("search_dlg", "Dialog"))
        self.pushButton.setText(_translate("search_dlg", "Search"))
        self.checkBox.setText(_translate("search_dlg", "AF"))
        self.checkBox_2.setText(_translate("search_dlg", "impact"))
        self.comboBox.setCurrentText(_translate("search_dlg", "HIGH"))
        self.comboBox.setItemText(0, _translate("search_dlg", "HIGH"))
        self.comboBox.setItemText(1, _translate("search_dlg", "MEDIUM"))
        self.comboBox.setItemText(2, _translate("search_dlg", "LOW"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    search_dlg = QtWidgets.QDialog()
    ui = Ui_search_dlg()
    ui.setupUi(search_dlg)
    search_dlg.show()
    sys.exit(app.exec_())
